import type { CurriculumWeek, StudentProfile } from "./types";

export const STORAGE_KEY = "saisha-python-builder-progress-v1";

export const studentProfile: StudentProfile = {
  name: "Saisha",
  level: "Absolute Beginner",
  cadence: "12 weeks",
  currentWeek: 1,
};

const platform = {
  hackerRankPython: "https://www.hackerrank.com/domains/python",
  leetCodeEasy: "https://leetcode.com/problemset/?difficulty=EASY",
  gfgPython: "https://www.geeksforgeeks.org/python-programming-language/",
};

export const curriculum: CurriculumWeek[] = [
  {
    week: 1,
    month: "Month 1",
    level: "Programming Fundamentals",
    title: "Logic Building With Numbers",
    focus: "Variables, input/output, conditions, loops, and number problems.",
    concepts: ["Variables", "Input and output", "Conditions", "Loops", "Dry runs"],
    why: [
      "Variables let programs remember values like scores, marks, prices, and counters.",
      "Conditions help software decide what to do in attendance, billing, and login systems.",
      "Loops repeat work, like processing orders, marks, or feed items.",
    ],
    realWorld: [
      "A payroll system loops through employees to calculate salaries.",
      "A basketball scoreboard updates totals after every basket.",
      "A banking app checks conditions before approving a transaction.",
    ],
    visual: "Trace variables in a table while a loop processes each digit of a number.",
    problems: [
      {
        id: "w1-sum-digits",
        title: "Sum of Digits",
        difficulty: "Easy",
        goal: "Break a number into digits and add them.",
        platformLink: platform.hackerRankPython,
      },
      {
        id: "w1-reverse-number",
        title: "Reverse Number",
        difficulty: "Medium",
        goal: "Use remainder and division to rebuild a number backwards.",
      },
      {
        id: "w1-prime-basic",
        title: "Prime Number Checker",
        difficulty: "Challenge",
        goal: "Check whether a number has factors other than 1 and itself.",
        platformLink: platform.gfgPython,
      },
    ],
    magicalQuestions: [
      {
        id: "w1-count-digits",
        title: "Count Digits",
        methods: ["Loop by dividing by 10", "Use logarithm after the idea is clear"],
        lesson: "Same result, different thinking paths.",
      },
      {
        id: "w1-sum-1-n",
        title: "Sum 1 to N",
        methods: ["Loop accumulation", "Formula n * (n + 1) / 2"],
        lesson: "Engineering asks whether the program can become faster.",
      },
    ],
    project: {
      id: "project-basketball-score-analyzer",
      title: "Basketball Score Analyzer",
      brief: "Enter 1, 2, and 3 point shots, calculate total score, and report the best scoring type.",
    },
    homework: {
      id: "homework-week-1",
      practice: ["Find factorial of a number", "Count even and odd digits"],
      challenge: "Print all prime numbers from 1 to N.",
    },
    resources: {
      notes: "Tutor notes: dry-run every loop with a variable table before coding.",
      videos: ["Python variables and loops", "Beginner dry-run practice"],
      practice: ["HackerRank Python Introduction", "LeetCode easy math problems"],
      articles: ["Python input/output basics"],
    },
  },
  {
    week: 2,
    month: "Month 1",
    level: "Programming Fundamentals",
    title: "Number Patterns And Special Numbers",
    focus: "Palindrome, Armstrong, perfect number, prime revision, and patterns.",
    concepts: ["Palindrome", "Armstrong number", "Perfect number", "Nested loops", "Patterns"],
    why: [
      "Special number problems train careful step-by-step logic.",
      "Patterns teach nested loops, which later help with grids, tables, and matrix problems.",
      "Prime checking introduces brute force and optimized thinking.",
    ],
    realWorld: [
      "OTP and ID validation often depends on digit logic.",
      "UI layouts use repeated rows and columns like pattern problems.",
      "Encryption and HTTPS rely on prime number ideas at a higher level.",
    ],
    visual: "Draw nested loop boxes: outer loop controls rows, inner loop controls columns.",
    problems: [
      {
        id: "w2-palindrome",
        title: "Palindrome Number",
        difficulty: "Easy",
        goal: "Reverse a number and compare it with the original.",
      },
      {
        id: "w2-armstrong",
        title: "Armstrong Number",
        difficulty: "Medium",
        goal: "Raise each digit to the count of digits and compare the sum.",
      },
      {
        id: "w2-pattern-diamond",
        title: "Centered Star Pattern",
        difficulty: "Challenge",
        goal: "Use spaces and stars to create a symmetric pattern.",
      },
    ],
    magicalQuestions: [
      {
        id: "w2-prime-optimized",
        title: "Prime Number",
        methods: ["Check divisors up to n - 1", "Check divisors up to square root of n"],
        lesson: "Stopping early can make a program much more scalable.",
      },
      {
        id: "w2-palindrome-methods",
        title: "Palindrome",
        methods: ["Reverse the number mathematically", "Convert to string and compare"],
        lesson: "Python gives shortcuts, but math builds stronger fundamentals.",
      },
    ],
    project: {
      id: "project-number-analyzer",
      title: "Number Analyzer",
      brief: "Take one number and report whether it is prime, palindrome, Armstrong, perfect, even, or odd.",
    },
    homework: {
      id: "homework-week-2",
      practice: ["Print a triangle pattern", "Check if a number is perfect"],
      challenge: "Build a menu-driven number analyzer.",
    },
    resources: {
      notes: "Tutor notes: compare brute force and optimized prime checks with small and large inputs.",
      videos: ["Python nested loops", "Number programs for beginners"],
      practice: ["HackerRank Python loops", "GeeksForGeeks pattern programs"],
      articles: ["Pattern printing with nested loops"],
    },
  },
  {
    week: 3,
    month: "Month 1",
    level: "Programming Fundamentals",
    title: "Functions And Reusable Thinking",
    focus: "Functions, parameters, return values, and decomposing problems.",
    concepts: ["Function definition", "Parameters", "Return values", "Scope", "Decomposition"],
    why: [
      "Functions prevent repeated code in calculators, reports, and dashboards.",
      "Parameters let one function work for many inputs.",
      "Return values help connect small logic blocks into bigger applications.",
    ],
    realWorld: [
      "A grade system reuses one function to calculate each student's grade.",
      "Payment apps reuse validation functions before every transfer.",
      "Games use functions to calculate score, health, and level progress.",
    ],
    visual: "Show a function as an input-output machine with named inputs and one clear result.",
    problems: [
      {
        id: "w3-grade-function",
        title: "Grade Calculator Function",
        difficulty: "Easy",
        goal: "Return a grade based on marks.",
      },
      {
        id: "w3-prime-function",
        title: "Reusable Prime Function",
        difficulty: "Medium",
        goal: "Create is_prime(n) and use it in multiple problems.",
      },
      {
        id: "w3-menu-app",
        title: "Menu Driven Calculator",
        difficulty: "Challenge",
        goal: "Break a calculator into small functions.",
      },
    ],
    magicalQuestions: [
      {
        id: "w3-gcd",
        title: "GCD",
        methods: ["Compare factors", "Euclid algorithm"],
        lesson: "Better algorithms can make old problems feel new.",
      },
      {
        id: "w3-grade-design",
        title: "Grade Design",
        methods: ["Use if/elif chain", "Use a reusable function with clear boundaries"],
        lesson: "Clean structure matters as programs grow.",
      },
    ],
    project: {
      id: "project-grade-management",
      title: "Grade Management System",
      brief: "Enter marks for subjects, calculate total, average, grade, and pass/fail result using functions.",
    },
    homework: {
      id: "homework-week-3",
      practice: ["Write a function to find factorial", "Write a function to count vowels"],
      challenge: "Build a mini marksheet generator using functions.",
    },
    resources: {
      notes: "Tutor notes: require Saisha to explain what each function receives and returns.",
      videos: ["Python functions for beginners", "Function parameters and return values"],
      practice: ["HackerRank Python functions", "LeetCode easy function-style problems"],
      articles: ["Python function basics"],
    },
  },
  {
    week: 4,
    month: "Month 1",
    level: "Programming Fundamentals",
    title: "Lists And Linear Search",
    focus: "Lists, indexing, iteration, max/min, and searching.",
    concepts: ["Lists", "Indexing", "Append/update", "Iteration", "Linear search"],
    why: [
      "Lists store many related values, like scores, names, products, or expenses.",
      "Searching teaches how apps find records one by one.",
      "Indexing introduces the mental model needed for arrays and DSA.",
    ],
    realWorld: [
      "A cricket scoreboard stores player runs in a list.",
      "A shopping cart stores all selected items.",
      "Attendance software searches student names in a list.",
    ],
    visual: "Draw list boxes with index numbers above each item and values inside.",
    problems: [
      {
        id: "w4-max-score",
        title: "Find Highest Score",
        difficulty: "Easy",
        goal: "Loop through a list and track the maximum value.",
      },
      {
        id: "w4-linear-search",
        title: "Linear Search",
        difficulty: "Medium",
        goal: "Find whether a target exists in a list.",
      },
      {
        id: "w4-second-largest",
        title: "Second Largest Score",
        difficulty: "Challenge",
        goal: "Track the top two values without sorting.",
      },
    ],
    magicalQuestions: [
      {
        id: "w4-search-methods",
        title: "Find a Student",
        methods: ["Check every name manually", "Use Python's in operator after understanding the loop"],
        lesson: "Built-ins are powerful once the underlying logic is understood.",
      },
      {
        id: "w4-top-score",
        title: "Highest Score",
        methods: ["Sort and take last", "One-pass max tracking"],
        lesson: "Less work can produce the same answer.",
      },
    ],
    project: {
      id: "project-cricket-scoreboard",
      title: "Cricket Scoreboard",
      brief: "Store player names and runs, show total score, highest scorer, and search for a player.",
    },
    homework: {
      id: "homework-week-4",
      practice: ["Find average of list values", "Search a name in a list"],
      challenge: "Find the second highest score without using sort.",
    },
    resources: {
      notes: "Tutor notes: make Saisha trace index movement with arrows.",
      videos: ["Python lists", "Linear search explained"],
      practice: ["HackerRank Python lists", "LeetCode Two Sum after discussion"],
      articles: ["Python list operations"],
    },
  },
  {
    week: 5,
    month: "Month 2",
    level: "Software Development + DSA Basics",
    title: "Dictionaries And Fast Lookups",
    focus: "Key-value storage, records, counting, and lookup thinking.",
    concepts: ["Dictionaries", "Keys and values", "Records", "Frequency counting", "Lookup"],
    why: [
      "Dictionaries help apps find data quickly using a key.",
      "They model real objects like users, contacts, products, and students.",
      "Counting with dictionaries is a common problem-solving pattern.",
    ],
    realWorld: [
      "Instagram can find a user profile by username.",
      "A phone book maps names to phone numbers.",
      "A school database maps roll numbers to student details.",
    ],
    visual: "Show a two-column key-value table and connect keys to instant lookup.",
    problems: [
      {
        id: "w5-phone-lookup",
        title: "Phone Lookup",
        difficulty: "Easy",
        goal: "Find a phone number by contact name.",
      },
      {
        id: "w5-frequency",
        title: "Character Frequency",
        difficulty: "Medium",
        goal: "Count how many times each character appears.",
      },
      {
        id: "w5-student-rank",
        title: "Student Rank Finder",
        difficulty: "Challenge",
        goal: "Store students and marks, then find the highest performer.",
      },
    ],
    magicalQuestions: [
      {
        id: "w5-counting",
        title: "Count Repeated Items",
        methods: ["Nested loop counting", "Dictionary frequency counting"],
        lesson: "Choosing the right data structure can simplify the solution.",
      },
      {
        id: "w5-lookup",
        title: "Find a Contact",
        methods: ["Search a list of names", "Use name as dictionary key"],
        lesson: "Data organization changes speed and clarity.",
      },
    ],
    project: {
      id: "project-phone-book",
      title: "Phone Book + Student Database",
      brief: "Add, search, update, and list contacts or student records using dictionaries.",
    },
    homework: {
      id: "homework-week-5",
      practice: ["Count word frequency", "Create a student marks dictionary"],
      challenge: "Build a menu-driven phone book.",
    },
    resources: {
      notes: "Tutor notes: connect dictionary keys to real lookup systems.",
      videos: ["Python dictionaries", "Frequency counting pattern"],
      practice: ["HackerRank dictionaries and maps", "LeetCode easy hash map problems"],
      articles: ["Dictionary operations in Python"],
    },
  },
  {
    week: 6,
    month: "Month 2",
    level: "Software Development + DSA Basics",
    title: "Files And Persistent Data",
    focus: "Reading, writing, appending, and storing simple app data.",
    concepts: ["File read", "File write", "Append mode", "CSV-style data", "Persistence"],
    why: [
      "Files let programs remember data after the program closes.",
      "They prepare students for databases by teaching persistence first.",
      "Logs, reports, chats, and exports all depend on stored data.",
    ],
    realWorld: [
      "WhatsApp stores chat history.",
      "Expense apps save transaction records.",
      "Attendance systems export daily reports.",
    ],
    visual: "Draw program memory on one side and a saved file on the other side.",
    problems: [
      {
        id: "w6-save-expense",
        title: "Save One Expense",
        difficulty: "Easy",
        goal: "Write expense name and amount to a file.",
      },
      {
        id: "w6-read-total",
        title: "Read And Total Expenses",
        difficulty: "Medium",
        goal: "Read saved expenses and calculate total spending.",
      },
      {
        id: "w6-attendance-report",
        title: "Attendance Report",
        difficulty: "Challenge",
        goal: "Store attendance and generate a present/absent summary.",
      },
    ],
    magicalQuestions: [
      {
        id: "w6-memory-file",
        title: "Where Should Data Live?",
        methods: ["Keep data only in a list", "Write data to a file"],
        lesson: "Persistence is what turns a script into a usable tool.",
      },
      {
        id: "w6-reporting",
        title: "Generate Total",
        methods: ["Calculate while entering", "Save first and calculate while reading"],
        lesson: "Different flows fit different product needs.",
      },
    ],
    project: {
      id: "project-expense-tracker",
      title: "Expense Tracker + Attendance System",
      brief: "Save entries to a file, read them back, and show totals or attendance summaries.",
    },
    homework: {
      id: "homework-week-6",
      practice: ["Write names to a file", "Read marks from a file and find average"],
      challenge: "Build an expense tracker that stores and shows category totals.",
    },
    resources: {
      notes: "Tutor notes: discuss why localStorage in this app is similar to saving progress.",
      videos: ["Python file handling", "Beginner CSV files"],
      practice: ["HackerRank file handling references", "GeeksForGeeks file handling"],
      articles: ["Reading and writing files in Python"],
    },
  },
  {
    week: 7,
    month: "Month 2",
    level: "Software Development + DSA Basics",
    title: "Search And Sort Foundations",
    focus: "Linear search, binary search, sorting, and simple complexity language.",
    concepts: ["Linear search", "Binary search", "Sorting", "Brute force", "Optimized solution"],
    why: [
      "Search powers student records, product search, and profile lookup.",
      "Sorting helps rank scores, prices, dates, and leaderboard entries.",
      "Complexity language helps compare fast, slow, and scalable approaches.",
    ],
    realWorld: [
      "Google-style search depends on organized data and fast lookup.",
      "E-commerce apps sort products by price and rating.",
      "A leaderboard ranks players by XP or score.",
    ],
    visual: "Animate binary search by crossing out half of a sorted list at each step.",
    problems: [
      {
        id: "w7-linear-search",
        title: "Student Linear Search",
        difficulty: "Easy",
        goal: "Search student names one by one.",
      },
      {
        id: "w7-binary-search",
        title: "Binary Search",
        difficulty: "Medium",
        goal: "Find a target in a sorted list by halving the search area.",
        platformLink: platform.leetCodeEasy,
      },
      {
        id: "w7-sort-ranks",
        title: "Sort Leaderboard",
        difficulty: "Challenge",
        goal: "Sort students by score and display ranks.",
      },
    ],
    magicalQuestions: [
      {
        id: "w7-search-comparison",
        title: "Find Roll Number",
        methods: ["Linear search in any list", "Binary search in a sorted list"],
        lesson: "Preparation of data can unlock faster algorithms.",
      },
      {
        id: "w7-sorting",
        title: "Rank Scores",
        methods: ["Repeatedly find maximum", "Use sorting"],
        lesson: "Readable solutions and scalable solutions must both be discussed.",
      },
    ],
    project: {
      id: "project-student-search",
      title: "Student Search System + Leaderboard",
      brief: "Search students by roll number and show a sorted score leaderboard.",
    },
    homework: {
      id: "homework-week-7",
      practice: ["Implement binary search", "Sort a list of marks"],
      challenge: "Compare linear and binary search step counts for different list sizes.",
    },
    resources: {
      notes: "Tutor notes: keep complexity simple: fast, slow, scalable.",
      videos: ["Binary search visual explanation", "Sorting basics"],
      practice: ["LeetCode Binary Search", "HackerRank sorting problems"],
      articles: ["Binary search beginner explanation"],
    },
  },
  {
    week: 8,
    month: "Month 2",
    level: "Software Development + DSA Basics",
    title: "OOP And Modeling Real Systems",
    focus: "Classes, objects, attributes, methods, and app structure.",
    concepts: ["Classes", "Objects", "Attributes", "Methods", "Object lists"],
    why: [
      "OOP helps model real entities like students, players, products, and accounts.",
      "Classes group data and behavior together.",
      "OOP prepares students for larger full stack and mobile projects.",
    ],
    realWorld: [
      "A student management system stores each student as an object.",
      "A basketball game stores each player with score, fouls, and position.",
      "A banking system models accounts with balance and actions.",
    ],
    visual: "Draw a class blueprint and multiple objects created from it.",
    problems: [
      {
        id: "w8-student-class",
        title: "Student Class",
        difficulty: "Easy",
        goal: "Create a Student class with name, roll number, and marks.",
      },
      {
        id: "w8-player-methods",
        title: "Basketball Player Methods",
        difficulty: "Medium",
        goal: "Add methods to update points and show player summary.",
      },
      {
        id: "w8-management-system",
        title: "Student Management System",
        difficulty: "Challenge",
        goal: "Store multiple objects and search/update them.",
      },
    ],
    magicalQuestions: [
      {
        id: "w8-dict-vs-class",
        title: "Student Record",
        methods: ["Use dictionaries", "Use a Student class"],
        lesson: "The best representation depends on how the program will grow.",
      },
      {
        id: "w8-methods",
        title: "Update Score",
        methods: ["Write separate functions", "Attach behavior to the object as methods"],
        lesson: "OOP can make product code easier to organize.",
      },
    ],
    project: {
      id: "project-player-management",
      title: "Basketball Player Management",
      brief: "Create player objects, update scores, list players, and find the top scorer.",
    },
    homework: {
      id: "homework-week-8",
      practice: ["Create a BankAccount class", "Create a Book class"],
      challenge: "Build a student management system using classes.",
    },
    resources: {
      notes: "Tutor notes: introduce OOP as modeling, not just syntax.",
      videos: ["Python OOP for beginners", "Classes and objects visualized"],
      practice: ["GeeksForGeeks OOP exercises", "Beginner class practice"],
      articles: ["Python classes overview"],
    },
  },
  {
    week: 9,
    month: "Month 3",
    level: "Web Development",
    title: "HTML And Page Structure",
    focus: "HTML tags, page sections, links, images, and semantic structure.",
    concepts: ["HTML document", "Headings", "Paragraphs", "Links", "Images", "Forms"],
    why: [
      "HTML is the structure of every website.",
      "Forms collect user input for real applications.",
      "Semantic sections make pages easier to read and maintain.",
    ],
    realWorld: [
      "Portfolio websites use sections for intro, skills, projects, and contact.",
      "College websites use links, tables, forms, and announcements.",
      "Product pages use images, headings, and structured details.",
    ],
    visual: "Map a webpage screenshot to nested HTML boxes.",
    problems: [
      {
        id: "w9-profile-page",
        title: "Profile Page Markup",
        difficulty: "Easy",
        goal: "Create headings, paragraphs, links, and image structure.",
      },
      {
        id: "w9-contact-form",
        title: "Contact Form",
        difficulty: "Medium",
        goal: "Build a form with name, email, message, and button.",
      },
      {
        id: "w9-project-list",
        title: "Project Listing Page",
        difficulty: "Challenge",
        goal: "Structure multiple projects cleanly with semantic HTML.",
      },
    ],
    magicalQuestions: [
      {
        id: "w9-layout-structure",
        title: "Portfolio Sections",
        methods: ["Use generic divs", "Use semantic tags like header, main, section"],
        lesson: "Structure affects readability for humans and tools.",
      },
      {
        id: "w9-form-data",
        title: "Collect Input",
        methods: ["Use prompt in Python", "Use form inputs on a webpage"],
        lesson: "The same input idea appears in different platforms.",
      },
    ],
    project: {
      id: "project-portfolio-html",
      title: "Portfolio Website",
      brief: "Build Saisha's first HTML portfolio with intro, skills, projects, and contact sections.",
    },
    homework: {
      id: "homework-week-9",
      practice: ["Create an about-me page", "Create a contact form"],
      challenge: "Create a project gallery page with at least three projects.",
    },
    resources: {
      notes: "Tutor notes: connect HTML tags to the idea of data structure on a page.",
      videos: ["HTML crash course", "Semantic HTML basics"],
      practice: ["FreeCodeCamp HTML basics", "MDN HTML references"],
      articles: ["MDN HTML getting started"],
    },
  },
  {
    week: 10,
    month: "Month 3",
    level: "Web Development",
    title: "CSS And Professional Styling",
    focus: "Selectors, box model, layout, colors, spacing, and responsive design.",
    concepts: ["CSS selectors", "Box model", "Flexbox", "Grid", "Responsive design"],
    why: [
      "CSS turns structure into a usable, polished interface.",
      "Spacing and alignment make information easier to scan.",
      "Responsive design makes pages work on phones and laptops.",
    ],
    realWorld: [
      "Portfolio design affects how recruiters understand a student.",
      "Dashboards use layout and spacing to make data readable.",
      "Mobile-first pages adapt to small screens.",
    ],
    visual: "Draw margin, border, padding, and content as nested boxes.",
    problems: [
      {
        id: "w10-style-card",
        title: "Style A Profile Card",
        difficulty: "Easy",
        goal: "Apply colors, spacing, border, and typography.",
      },
      {
        id: "w10-flex-layout",
        title: "Flexbox Navigation",
        difficulty: "Medium",
        goal: "Create a responsive navigation bar.",
      },
      {
        id: "w10-responsive-page",
        title: "Responsive Portfolio",
        difficulty: "Challenge",
        goal: "Make a portfolio adapt across mobile and desktop.",
      },
    ],
    magicalQuestions: [
      {
        id: "w10-layout-methods",
        title: "Arrange Cards",
        methods: ["Use flexbox", "Use CSS grid"],
        lesson: "Layout tools have different strengths.",
      },
      {
        id: "w10-responsive",
        title: "Mobile Design",
        methods: ["Fixed desktop width", "Responsive flexible layout"],
        lesson: "Products must adapt to the user device.",
      },
    ],
    project: {
      id: "project-professional-portfolio",
      title: "Professional Portfolio",
      brief: "Style the portfolio with responsive sections, project cards, and a polished contact area.",
    },
    homework: {
      id: "homework-week-10",
      practice: ["Style a button set", "Create a two-column layout"],
      challenge: "Make the portfolio responsive without breaking text or layout.",
    },
    resources: {
      notes: "Tutor notes: review spacing and alignment using real websites.",
      videos: ["CSS box model", "Flexbox and grid basics"],
      practice: ["CSS layout exercises", "Frontend Mentor beginner challenges"],
      articles: ["MDN CSS basics"],
    },
  },
  {
    week: 11,
    month: "Month 3",
    level: "Web Development",
    title: "JavaScript Basics For Interactive Pages",
    focus: "Variables, functions, conditions, events, and calculations in the browser.",
    concepts: ["JavaScript variables", "Functions", "Conditions", "Events", "Form values"],
    why: [
      "JavaScript makes webpages respond to user actions.",
      "Calculators and quizzes need browser-side logic.",
      "This bridges Python logic with frontend product building.",
    ],
    realWorld: [
      "Age calculators process user input instantly.",
      "Score calculators update totals without reloading.",
      "Shopping carts update prices as items change.",
    ],
    visual: "Show event flow: user action, event listener, function, updated result.",
    problems: [
      {
        id: "w11-age-calc",
        title: "Age Calculator",
        difficulty: "Easy",
        goal: "Read birth year and display age.",
      },
      {
        id: "w11-score-calc",
        title: "Score Calculator",
        difficulty: "Medium",
        goal: "Calculate total score from different point types.",
      },
      {
        id: "w11-form-validator",
        title: "Simple Form Validator",
        difficulty: "Challenge",
        goal: "Check required fields and show messages.",
      },
    ],
    magicalQuestions: [
      {
        id: "w11-python-js",
        title: "Same Calculator",
        methods: ["Build in Python console", "Build in JavaScript webpage"],
        lesson: "Core logic transfers across languages and platforms.",
      },
      {
        id: "w11-events",
        title: "When Should Code Run?",
        methods: ["Run immediately", "Run when a button is clicked"],
        lesson: "Interactive apps depend on events.",
      },
    ],
    project: {
      id: "project-score-calculator",
      title: "Age Calculator + Score Calculator",
      brief: "Build browser calculators that take input, run logic, and display results.",
    },
    homework: {
      id: "homework-week-11",
      practice: ["Build a tip calculator", "Build a pass/fail marks checker"],
      challenge: "Create a score calculator with validation messages.",
    },
    resources: {
      notes: "Tutor notes: repeatedly map Python syntax ideas to JavaScript syntax.",
      videos: ["JavaScript basics", "DOM events for beginners"],
      practice: ["JavaScript beginner exercises", "FreeCodeCamp JavaScript basics"],
      articles: ["MDN JavaScript first steps"],
    },
  },
  {
    week: 12,
    month: "Month 3",
    level: "Web Development",
    title: "DOM Manipulation And Mini Web Apps",
    focus: "Selecting elements, updating UI, lists, quiz logic, and final integration.",
    concepts: ["DOM selection", "Text updates", "Class changes", "Dynamic lists", "Quiz state"],
    why: [
      "DOM manipulation lets apps change what the user sees.",
      "Dynamic lists are the foundation of dashboards, carts, and trackers.",
      "Final projects combine structure, style, and logic.",
    ],
    realWorld: [
      "A basketball statistics website updates player numbers.",
      "Quiz apps track answers, score, and progress.",
      "Task apps add and remove items on the page.",
    ],
    visual: "Draw the DOM tree and highlight which node changes after a click.",
    problems: [
      {
        id: "w12-change-result",
        title: "Update Result Text",
        difficulty: "Easy",
        goal: "Change text on the page after a button click.",
      },
      {
        id: "w12-dynamic-list",
        title: "Dynamic Player List",
        difficulty: "Medium",
        goal: "Add player scores to a visible list.",
      },
      {
        id: "w12-quiz",
        title: "Quiz Application",
        difficulty: "Challenge",
        goal: "Track questions, answers, score, and final result.",
      },
    ],
    magicalQuestions: [
      {
        id: "w12-render-list",
        title: "Show Many Items",
        methods: ["Write static HTML repeatedly", "Generate elements from an array"],
        lesson: "Data-driven rendering is the heart of modern frontend apps.",
      },
      {
        id: "w12-state",
        title: "Track Quiz Score",
        methods: ["Use separate variables", "Use one state object"],
        lesson: "Good state design keeps app behavior predictable.",
      },
    ],
    project: {
      id: "project-basketball-stats-quiz",
      title: "Basketball Statistics Website + Quiz Application",
      brief: "Build a final mini web app with dynamic stats, quiz questions, score, and progress display.",
    },
    homework: {
      id: "homework-week-12",
      practice: ["Create a dynamic todo list", "Build a three-question quiz"],
      challenge: "Combine portfolio, calculator, and quiz into one polished mini site.",
    },
    resources: {
      notes: "Tutor notes: celebrate the full path from Python logic to web product.",
      videos: ["DOM manipulation basics", "Build a JavaScript quiz"],
      practice: ["DOM exercises", "Frontend Mentor beginner interactive challenges"],
      articles: ["MDN DOM introduction"],
    },
  },
  {
    week: 13,
    month: "Month 4",
    level: "Professional Development",
    title: "Version Control With Git & GitHub",
    focus: "Repositories, commits, push/pull, branching, and collaboration.",
    concepts: ["Git", "GitHub", "Repos", "Commits", "Push & Pull", "Branching"],
    why: [
      "Version control lets you track every change in your code history.",
      "GitHub acts as a professional portfolio for engineers.",
      "Branching allows safe experimentation without breaking the main product.",
    ],
    realWorld: [
      "Every major tech company uses Git to manage massive codebases like Windows or WhatsApp.",
      "Open source projects like Linux or React are built by thousands of people via GitHub.",
      "Teams use branching to fix bugs while others build new features.",
    ],
    visual: "Draw a timeline of commits and branching paths emerging from the main line.",
    problems: [
      {
        id: "w13-git-init",
        title: "Initialize A Repository",
        difficulty: "Easy",
        goal: "Set up a local Git repo and track files.",
      },
      {
        id: "w13-push-github",
        title: "Push To GitHub",
        difficulty: "Medium",
        goal: "Link local repo to GitHub and push your first commit.",
      },
      {
        id: "w13-resolve-conflict",
        title: "Merge & Branch basics",
        difficulty: "Challenge",
        goal: "Create a branch, make changes, and merge it back.",
      },
    ],
    magicalQuestions: [
      {
        id: "w13-history",
        title: "Safe to Fail",
        methods: ["Keep copies of files (v1, v2, final)", "Use Git commits"],
        lesson: "Git makes code failures temporary and recoverable.",
      },
      {
        id: "w13-open-source",
        title: "Public Portfolio",
        methods: ["Keep code hidden", "Share code on GitHub"],
        lesson: "Visibility builds professional credibility.",
      },
    ],
    project: {
      id: "project-github-portfolio",
      title: "GitHub Portfolio Kickstart",
      brief: "Host all previous Python and Web projects on GitHub with professional README documentation.",
    },
    homework: {
      id: "homework-week-13",
      practice: ["Commit a new file", "Create a GitHub repository"],
      challenge: "Write a detailed README for your best project so far.",
    },
    resources: {
      notes: "Tutor notes: focus on the 'why' of history tracking before command syntax.",
      videos: ["Git & GitHub for absolute beginners", "Understanding branching"],
      practice: ["Learn Git Branching interactive game", "GitHub Hello World guide"],
      articles: ["Git handbook by GitHub"],
    },
  },
  {
    week: 14,
    month: "Month 4",
    level: "Professional Development",
    title: "Deployment & Portfolio Live",
    focus: "Deployment pipelines, Vercel, Netlify, custom domains, and live updates.",
    concepts: ["Deployment", "Build pipeline", "Vercel", "Netlify", "Site settings"],
    why: [
      "Deployment takes your code from a laptop to the global internet.",
      "Auto-deployment syncs your GitHub changes to your live site instantly.",
      "Sharing a live link is the ultimate proof of a built product.",
    ],
    realWorld: [
      "Vercel and Netlify power millions of modern websites including major tech blogs.",
      "Automated pipelines ensure the live app is always the latest stable version.",
      "Custom domains turn a 'project' into a 'brand'.",
    ],
    visual: "Draw a path: Code -> Push to GitHub -> Trigger Build -> Live URL.",
    problems: [
      {
        id: "w14-vercel-deploy",
        title: "Deploy To Vercel",
        difficulty: "Easy",
        goal: "Link a GitHub repo to Vercel and get a live URL.",
      },
      {
        id: "w14-update-live",
        title: "Live Update Cycle",
        difficulty: "Medium",
        goal: "Push a change to GitHub and watch Vercel update the live site automatically.",
      },
      {
        id: "w14-site-polish",
        title: "Custom Settings",
        difficulty: "Challenge",
        goal: "Set custom site name and verify meta data.",
      },
    ],
    magicalQuestions: [
      {
        id: "w14-local-vs-live",
        title: "Proof of Work",
        methods: ["Show screenshot of code", "Send a live URL"],
        lesson: "A live product solves the trust problem for developers.",
      },
      {
        id: "w14-automation",
        title: "Continuous Delivery",
        methods: ["Upload files manually", "Automate via GitHub sync"],
        lesson: "Automation lets developers focus on building, not maintenance.",
      },
    ],
    project: {
      id: "project-final-portfolio-launch",
      title: "Final Portfolio Launch",
      brief: "Launch your full responsive portfolio and mini-apps live for the world to see.",
    },
    homework: {
      id: "homework-week-14",
      practice: ["Deploy a mini-app", "Verify responsive layout on phone"],
      challenge: "Add a 'Built with...' badge to your live footer.",
    },
    resources: {
      notes: "Tutor notes: verify the mobile view of the deployed site with Saisha.",
      videos: ["Deploying to Vercel", "Netlify basics for beginners"],
      practice: ["Vercel documentation guides", "Netlify docs"],
      articles: ["What is Deployment?"],
    },
  },
];
